######################################################################
# Automatically generated by qmake (3.0) ?? 5? 7 15:26:15 2017
######################################################################

QT += core
QT += widgets
QT += gui

TEMPLATE = app
TARGET = color
INCLUDEPATH += .

CONFIG += link_pkgconfig
CONFIG += c++11

# Input
HEADERS += main_window.h color_label.h full_window.h
SOURCES += main.cpp main_window.cpp color_label.cpp full_window.cpp

QMAKE_CXXFLAGS += -g
